on:
  pull_request:
    paths:
    - '**/Dockerfile'

name: Docker scan

jobs:
  anchore:
    name: Docker image vulnerability scan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
        - api
        - client

    steps:

    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        file: ${{ matrix.service }}/Dockerfile
        load: true
        tags: ${{ github.repository }}-${{ matrix.service }}:${{ github.sha }}

    - name: Scan Docker image
      uses: anchore/scan-action@v1
      id: anchore-scan
      with:
        image-reference: ${{ github.repository }}-${{ matrix.service }}:${{ github.sha }}
        fail-build: true
